version: "3.8"
services:
  db:
    image: library/mysql:5.7
    restart: always
    volumes:
    - /root/mysql/data:/var/lib/mysql
    - /root/mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_HOST: 192.168.136.132
    ports:
    - "3306:3306"
  web:
    build: .
    depends_on:
      - db
    restart: always
    ports:
    - "8031:8031"
